# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("RIGHT_SENSE does not double the interval",
     "interval = min(int(record.interval) * 2, MAX_INTERVAL_DAYS)",
     "interval = min(int(record.interval) * 1, MAX_INTERVAL_DAYS)"),
    ("interval has no 32-day cap",
     "interval = min(int(record.interval) * 2, MAX_INTERVAL_DAYS)",
     "interval = int(record.interval) * 2"),
    ("OTHER_SENSE keeps the interval instead of collapsing to 1",
     "        else:\n            interval = 1\n",
     "        else:\n            interval = int(record.interval)\n"),
    ("next due day ignores the new interval",
     "record.due_day = u256(today + interval)", "record.due_day = u256(today + 1)"),
    ("due check off by one (due day itself refused)",
     "if today < int(record.due_day):", "if today <= int(record.due_day):"),
    ("new card not due on the day it is added",
     "due_day=u256(self._today()),", "due_day=u256(self._today() + 1),"),
    ("rights not counted",
     "record.rights = u256(int(record.rights) + 1)", "record.rights = u256(int(record.rights))"),
    ("fail-safe flipped on unparseable output",
     "                    return {\"outcome\": OTHER_SENSE}\n            if not isinstance(data, dict):",
     "                    return {\"outcome\": RIGHT_SENSE}\n            if not isinstance(data, dict):"),
    ("unknown label maps to RIGHT_SENSE",
     "            if outcome == RIGHT_SENSE:\n                return {\"outcome\": RIGHT_SENSE}\n            return {\"outcome\": OTHER_SENSE}",
     "            if outcome == OTHER_SENSE:\n                return {\"outcome\": OTHER_SENSE}\n            return {\"outcome\": RIGHT_SENSE}"),
    ("validator accepts any valid label",
     "                return str(mine.get(\"outcome\", \"\")).strip().upper() == leader_outcome",
     "                return True"),
    ("anyone may practise a card",
     "        if caller != record.owner:", "        if caller == \"\":"),
    ("due checked before owner",
     "        if caller != record.owner:\n            raise gl.vm.UserError(\"Only the card's owner may practise it\")\n        today = self._today()\n        if today < int(record.due_day):\n            raise gl.vm.UserError(\"This card is not due yet\")",
     "        today = self._today()\n        if today < int(record.due_day):\n            raise gl.vm.UserError(\"This card is not due yet\")\n        if caller != record.owner:\n            raise gl.vm.UserError(\"Only the card's owner may practise it\")"),
    ("same sentence may be reused",
     "        if used in self.used:", "        if used in self.used and False:"),
    ("used key not lower-cased (case grinding)",
     "        key = self._normalize_text(sentence).lower()", "        key = self._normalize_text(sentence)"),
    ("used key not whitespace-normalized (spacing grinding)",
     "        key = self._normalize_text(sentence).lower()", "        key = sentence.lower()"),
    ("term check skipped",
     "        if not self._uses_term(clean, record.term):", "        if False:"),
    ("term check: no boundary after the term (banks / banked accepted)",
     "            after_ok = end == len(hay) or not hay[end].isalpha()", "            after_ok = True"),
    ("term check: no boundary before the term (riverbank accepted)",
     "            before_ok = start == 0 or not hay[start - 1].isalpha()", "            before_ok = True"),
    ("term check is case-sensitive",
     "        hay = self._normalize_text(sentence).lower()", "        hay = self._normalize_text(sentence)"),
    ("term check looks at the first occurrence only",
     "            start = hay.find(needle, start + 1)", "            start = -1"),
    ("reserved token not checked on sentences",
     "            raise gl.vm.UserError(\"Sentence is too long\")\n        if self._contains_reserved_token(clean):",
     "            raise gl.vm.UserError(\"Sentence is too long\")\n        if False:"),
    ("reserved token not checked on the sense",
     "if self._contains_reserved_token(clean_term) or self._contains_reserved_token(clean_sense):",
     "if self._contains_reserved_token(clean_term):"),
    ("deck cap off by one (51 cards)",
     "        if count >= MAX_CARDS_PER_OWNER:", "        if count > MAX_CARDS_PER_OWNER:"),
    ("sentence length cap off by one",
     "        if len(clean) > MAX_SENTENCE_LENGTH:", "        if len(clean) >= MAX_SENTENCE_LENGTH:"),
    ("card id ignores whitespace normalization",
     "cid = self._card_id(owner, self._normalize_text(clean_term), self._normalize_text(clean_sense))",
     "cid = self._card_id(owner, clean_term, clean_sense)"),
    ("owner missing from the card id",
     "        payload = (\"WORD_SENSE:CARD:V1|\" + owner.lower()", "        payload = (\"WORD_SENSE:CARD:V1|\" + \"x\""),
    ("fence strip: no gap and a single pass (cross-token rebuild survives)",
     "            cleaned = cleaned[:index] + \" \" + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        # Fixed point: repeat until nothing changes, so nested fragments\n        # such as \"<<TAG>TAG>\" cannot rebuild a marker after one pass.\n        cleaned = value\n        while True:\n            before = cleaned\n            for token in RESERVED_TOKENS:\n                cleaned = self._remove_token(cleaned, token)\n            if cleaned == before:\n                return \" \".join(cleaned.split())",
     "            cleaned = cleaned[:index] + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        cleaned = value\n        for token in RESERVED_TOKENS:\n            cleaned = self._remove_token(cleaned, token)\n        return \" \".join(cleaned.split())"),
    ("wallet leaks into the prompt",
     "        safe_sentence = self._fence_strip(sentence)",
     "        safe_sentence = self._fence_strip(sentence) + \" \" + str(gl.message.sender_address)"),
    ("day helper: leap shift on the wrong months",
     "        y -= m <= 2", "        y -= m < 2"),
    ("deck view not sorted by due day",
     "        rows.sort(key=lambda item: (item[\"due_day\"], item[\"index\"]))", "        pass"),
]
